version: "3.7"
services: 
  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - 15671:15671
      - 15672:15672
      - 5671:5671
      - 5672:5672
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
